/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lgtDxztfD5y
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function KidneyForm() {
  return (
    <div className="flex justify-center">
      <Card className="w-full max-w-3xl bg-gradient-to-br from-gray-900 to-gray-400 rounded-lg p-6">
        <CardHeader>
          <CardTitle className="text-white">Medical Diagnosis</CardTitle>
          <CardDescription className="text-white">
            Enter the patient's information to assess the risk of disease.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label className="text-white" htmlFor="name">
                Name
              </Label>
              <Input className="bg-white text-gray-800 rounded-md p-2" id="name" placeholder="Name" required />
            </div>
            <div className="space-y-2">
              <Label className="text-white" htmlFor="age">
                Age
              </Label>
              <Input className="bg-white text-gray-800 rounded-md p-2" id="age" placeholder="Age" required />
            </div>
            <div className="space-y-2">
              <Label className="text-white" htmlFor="gender">
                Gender
              </Label>
              <Input className="bg-white text-gray-800 rounded-md p-2" id="gender" placeholder="Gender" required />
            </div>
            <div className="space-y-2">
              <Label className="text-white" htmlFor="history">
                Medical History
              </Label>
              <Input className="bg-white text-gray-800 rounded-md p-2" id="gender" placeholder="Gender" required />
            </div>
            <div className="space-y-2">
              <Label className="text-white" htmlFor="symptoms">
                Symptoms
              </Label>
              <Input className="bg-white text-gray-800 rounded-md p-2" id="gender" placeholder="Gender" required />
            </div>
            <div className="space-y-2">
              <Label className="text-white" htmlFor="tests">
                Test Results
              </Label>
              <Input className="bg-white text-gray-800 rounded-md p-2" id="gender" placeholder="Gender" required />
            </div>
          </div>
          <Button className="w-full bg-white text-purple-500 hover:bg-purple-500 hover:text-white">Assess Risk</Button>
        </CardContent>
      </Card>
    </div>
  )
}
